import { Suspense } from "react";

import { SectionTutorial } from "@/components/SectionTutorial";
import { SurfaceExplorer } from "@/components/SurfaceExplorer";

export const metadata = {
  title: "Surface Waves — multivariable explorer | Ondas",
  description:
    "Hear z = f(x, y) as spatial sound: an Archimedean spiral through a 3D panner, with height mapped to pitch.",
};

export default function MultivariablePage() {
  return (
    <Suspense fallback={<p className="px-6 py-10 text-zinc-500">Loading the surface explorer…</p>}>
      <SectionTutorial
        storageKey="ondas-tutorial-multivariable"
        script="Multivariable calculus. Hear 3D surfaces generated by functions of two variables. The sound will perform a smooth spiral scan, starting from the center of your head and expanding outwards. As the spiral moves around you, the pitch will rise and fall continuously to represent the height and depth of the mathematical surface."
      />
      <SurfaceExplorer />
    </Suspense>
  );
}
